### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by mbechler** [hankcs/AhoCorasickDoubleArrayTrie#4]
Hi,

thanks for that awesomely efficient implementation. Can you clarify on the licensing? README.MD states Apache License but the code files have some "custom" license statements (which is not that clear about what is allowed).

**Comment by hankcs** [comment]
Hi,

Don't worry about it, it is just a kind reminder. 
Since some guys(especially in China) just copied the code but removed the Apache  License and author name, even put their names on it, as if they wrote it. They behave like a theft, which makes me unhappy.

I have put the Apache  License in the file header now, enjoy it.

**Comment by mbechler** [comment]
Great, thanks.
